name: Unity WebGL Automatic Build 👽✨🚀

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Unity Build 👽
    runs-on: ubuntu-latest

    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      # Git LFS Pull
      - name: Git LFS Pull
        run: |
          git lfs install
          git lfs pull
          echo "Git LFS files pulled."

      # Cache Unity Library
      - name: Cache Library directory
        uses: actions/cache@v3
        id: unity-cache
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Verify Library Cache
        run: |
          echo "Library directory contents:"
          ls -al Library || echo "Library directory does not exist"

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildsPath: ./Builds
          allowDirtyBuild: true

      # Upload Build Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: UnityBuild
          path: ./Builds/

      # Deployment
      - name: Push Build artifact to deb-build branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.email "prathamesh@underpinservices.com"
          git config --global user.name "Prathm0025"
          git checkout -b deb-build || git checkout deb-build
          cp -r ./Builds/* ./  # Copy build files to root
          git add -f .
          git commit -m "Updated build artifacts"
          git push origin dev-build --force
