name: Unity WebGL Automatic Build 👽✨🚀

on:
  push:
    branches:    
      - 'develop'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Unity Build 👽
    runs-on: ubuntu-latest

    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}


      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          ls
          git reset --hard
          
      # Cache Unity Library
      - name: Cache Library directory
        uses: actions/cache@v3
        id: unity-cache
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Verify Library Cache
        run: |
          echo "Library directory contents:"
          ls -al Library || echo "Library directory does not exist"
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildsPath: ./Build
          allowDirtyBuild: true

      # Output: Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./Build/*

      # Deployment
      - name: Copy Build artifact in deb-build branch
        run: |
          git branch
          ls
          git stash -u
          ls
          git checkout dev-build
          ls
          git rm -rf Build
          git checkout develop --  Build
          ls
          git add -f .
          git commit -m "add new build" || echo "No changes to commit"
          git push origin dev-build